config/routes.rb
Rails.application.routes.draw do
  namespace :product do
    resources :products
  end
  root     "home#index"

  devise_for :users, controllers: {sessions: "users/sessions", passwords: 'users/passwords',  registrations: 'users/registrations', :confirmations => "users/confirmations" , :unlocks => 'users/unlocks'}
  #configuración para la gema auto-session-timeout
  devise_scope :user do
    match 'active'            => 'users/sessions#active',               via: :get  
    match 'timeout'           => 'users/sessions#timeout',              via: :get   
  end 
  
  get 'list', to: 'home#list'
  get 'list_search', to: 'home#list_search'
  get 'redireccionamiento_verificar', to: 'home#redireccionamiento_verificar'
  get 'plist', to: 'home#plist'
  get 'details/:id', to: 'home#details'
  get 'promotion/:id', to: 'home#promotion'
  get 'promotions', to: 'home#promotions'
  get 'pymes_promotions', to: 'home#pymes_promotions'
  get 'cart', to: 'home#cart'
  get 'quotation_history', to: 'home#quotation_history'
  get 'plan_history', to: 'home#plan_history'
  get 'expired_quotation', to: 'home#expired_quotation'
  get 'clinics', to: 'home#clinics'
  get 'clinics/:id', to: 'home#clinics_details'
  get 'admin', to: 'admin#index'
  get 'decision', to: 'home#decision'
  get 'message', to: 'home#message'
  get "blocked_user", to: "employees#blocked_user"
  get "forget_username", to: "employees#forget_username"
  get "forget_username_list", to: "employees#forget_username_list"
  get "forget_password", to: "employees#forget_password"
  post "check_send_username", to: "employees#check_send_username"
  get ':id/transference' , to: 'home#transference'
  get 'decision_transference', to: 'home#decision_transference'
  get 'profile', to: 'employees#profile'

  resources :people
  resources :organizations
  resources :initial_values
  resources :contacts

  resources :positions
    put "/positions/:id/inhabilitar", to:"positions#inhabilitar"
    put "/positions/:id/habilitar", to:"positions#habilitar"

  resources :specialities
    put "/specialities/:id/inhabilitar", to:"specialities#inhabilitar"
    put "/specialities/:id/habilitar", to:"specialities#habilitar"

  resources :banks
    put "/banks/:id/habilitar", to: "banks#habilitar"
    put "/banks/:id/inhabilitar", to: "banks#inhabilitar"

  resources :motives
    put "/motives/:id/inhabilitar", to:"motives#inhabilitar"
    put "/motives/:id/habilitar", to:"motives#habilitar"

  resources :method_payments
    put "/method_payments/:id/inhabilitar", to:"method_payments#inhabilitar"
    put "/method_payments/:id/habilitar", to:"method_payments#habilitar"

  resources :beneficiaries
    put "/beneficiaries/:id/inhabilitar", to: "beneficiaries#inhabilitar"
    put "/beneficiaries/:id/habilitar", to: "beneficiaries#habilitar"

  resources :customers
    put "/customers/:id/habilitar", to: "customers#habilitar"
    put "/customers/:id/inhabilitar", to: "customers#inhabilitar"

  resources :employees
    post "/employees/:id/habilitar", to: "employees#habilitar"
    post '/employees/:id/inhabilitar', to: "employees#inhabilitar"
    get '/employees/:id/motive', to: 'employees#motive'
    post "/employees/:id/eliminar_logico", to: "employees#eliminar_logico"
    put "/employees/:id/unblocked", to: "employees#unblocked"
    put "/employees/:id/resend_username", to: "employees#resend_username"
    put "/employees/:id/resend_password", to: "employees#resend_password"
    post '/employees/:id/update_user',to: 'employees#update_user'
    get "/employees/:id/redireccionamiento_eliminar", to: "employees#redireccionamiento_eliminar"
    get "/employees/:id/show_list", to: "employees#show_list"

  resources :accounts
    put "/accounts/:id/habilitar", to: "accounts#habilitar"
    put "/accounts/:id/inhabilitar", to: "accounts#inhabilitar"


  namespace :colection do
    resources :packages
      put "/packages/:id/habilitar", to: "packages#habilitar"
      put "/packages/:id/inhabilitar", to: "packages#inhabilitar"
      get "/packages/:id/destroy_package_product", to: "packages#destroy_package_product"
      get "/packages/:id/verificar_productos", to: "packages#verificar_productos"

    resources :package_products
  end

  namespace :product do
    resources :product_types
      put "/product_types/:id/inhabilitar", to:"product_types#inhabilitar"
      put "/product_types/:id/habilitar", to:"product_types#habilitar"

    resources :products
      put "/products/:id/inhabilitar", to:"products#inhabilitar"
      put "/products/:id/habilitar", to:"products#habilitar"

    resources :product_providers
  end

  namespace :business do
    resources :companies
      put "/company_types/:id/inhabilitar", to:"company_types#inhabilitar"
      put "/company_types/:id/habilitar", to:"company_types#habilitar"

    resources :company_types
      put "/companies/:id/inhabilitar", to:"companies#inhabilitar"
      put "/companies/:id/habilitar", to:"companies#habilitar"
  end

  namespace :security do
    resources :profiles
      post "/profiles/:id/inhabilitar", to:"profiles#inhabilitar"
      put "/profiles/:id/habilitar", to:"profiles#habilitar"
      get '/profiles/:id/motive', to: 'profiles#motive'

    resources :roles
      put "/roles/:id/inhabilitar", to:"roles#inhabilitar"
      put "/roles/:id/habilitar", to:"roles#habilitar"
      get 'redir', to: 'roles#redir'

    resources :role_types
      put "/role_types/:id/inhabilitar", to:"role_types#inhabilitar"
      put "/role_types/:id/habilitar", to:"role_types#habilitar"
    resources :role_type_menus
    resources :role_profiles
    resources :role_menus
  end

  namespace :provider do
    resources :provider_types
      put "/provider_types/:id/inhabilitar", to:"provider_types#inhabilitar"
      put "/provider_types/:id/habilitar", to:"provider_types#habilitar"

    resources :providers
      put "/providers/:id/inhabilitar", to:"providers#inhabilitar"
      put "/providers/:id/habilitar", to:"providers#habilitar"

    resources :medicos
      put "/medicos/:id/inhabilitar", to:"medicos#inhabilitar"
      put "/medicos/:id/habilitar", to:"medicos#habilitar"

    resources :medico_providers
  end

      get 'sale/quotations/reporte', to: "sale/quotations#reporte"
  namespace :sale do
    get 'actualizar_cantidad', to: 'package_quotations#actualizar_cantidad'
    get 'actualizar_cantidad_producto', to: 'product_quotations#actualizar_cantidad_producto'
    resources :quotations
      put "/quotations/:id/pagar", to:"quotations#pagar"
      put "/quotations/:id/cotizar", to:"quotations#cotizar"
      put "/quotations/:id/comprobante", to:"quotations#comprobante"
      put "/quotations/:id/reactivar", to:"quotations#reactivar"

      get 'quotations/:id/pay' , to: 'quotations#pay'
      get '/reactivar' , to: 'quotations#reactivate'
      get 'quotations/:id/view' , to: 'quotations#view'

    resources :package_quotations
    resources :product_quotations
  end

  namespace :payment do
    get 'contracted_products', to: "contracted_products#index"
    get 'contracted_products/:id', to: "contracted_products#show"
    resources :plans
    get 'plans_cierre' , to: 'plans#cierre'

    resources :transferences, only: [:new, :create]
  end

  namespace :service do
    resources :services
      put "/services/:id/reagendar", to: "services#reagendar"
      put "/services/:id/cancelar", to: "services#cancelar"
      put "/services/:id/anular", to: "services#anular"
    get 'reports' , to: 'services#report'

  end

  namespace :clinic do
    get 'clinic_service', to: "clinic_service#index"
    put "clinic_service/:id/atender", to: "clinic_service#atender"
    get 'reports', to: "clinic_service#report"
    get 'report_active', to: "clinic_service#report_active"
    get 'pending_date', to: "clinic_service#pending_date"
  end
  match '*path', to: redirect('/'), via: :all
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :title
  before_action :set_organization
  before_action :set_quotation
  before_action :set_product, only: [:details]
  before_action :verificar_usuario
  before_action :set_package, only: [:promotion]
  layout :set_layout
  add_breadcrumb "Inicio", :root_path
  def index
    session[:controller_layout] = params[:controller]
    session[:layout_action] = params[:action]
    @titulobanner= "Nuestros Productos"
    search(params[:search], params[:param_id_speciality])
  end

  def authorize_action
    if !(current_user.can?(:admin) ||
      current_user.eql?(@objeto.created_by) ||
      current_user.can?(params[:action].to_sym, @objeto))
      render 'errors/403', status: 403, layout: 'application'
    end
  end

  #despues de verificar si existen productos de distintos segmentos redirecciona
  def redireccionamiento_verificar
    @cotizacion_temporal = Sale::Quotation.find_by(ip_quotation: request.remote_ip, user_id: nil)
    @product_quotations = @cotizacion_temporal.sale_product_quotations.order(id: :asc)
    $producto = 0
    if params[:cliente]== "persona"
      @product_quotations.each do |product|
        if (product.product_product.category == 'PYMES')
          $producto = 1
        end  
      end
      if $producto > 0
        redirect_to message_path(:cliente => "persona")
      else 
        redirect_to new_user_session_path(:cliente => "persona")
      end
    else
      @product_quotations.each do |product|
        if (product.product_product.category == 'Individual')
          $producto = 1
        end  
      end
      if $producto > 0
        redirect_to message_path(:cliente => "empresa")
      else 
        redirect_to new_user_session_path(:cliente => "empresa")
      end
    end  
  end



  def list
    if params[:param_id_speciality]=='0' 
      params[:param_id_speciality]=''
    end
    @product_quotation = Sale::ProductQuotation.last
    @titulobanner= "Nuestros Servicios"

    respond_to do |format|
     if params[:search] && params[:param_id_speciality]==""
      format.html { @products = Product::Product.no_cero.activo.individual.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    elsif params[:search]=="" && params[:param_id_speciality]
      format.html { @products = Product::Product.no_cero.activo.individual.search_product_by_speciality(params[:param_id_speciality]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    elsif  params[:search] && params[:param_id_speciality] && params[:param_id_speciality]!=0
      format.html { @products = Product::Product.no_cero.activo.individual.search(params[:search]).search_product_by_speciality(params[:param_id_speciality]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    else
     format.html { @products = Product::Product.no_cero.activo.individual.order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
     format.json { @products = Product::Product.no_cero.activo }
     add_breadcrumb "Servicios", "/list"
   end   
 end
end


def list_search
  if $search
    params[:search] = $search 
    $search = nil
  end
  if $param_id_speciality
    params[:param_id_speciality] = $param_id_speciality 
    $param_id_speciality = nil
  end
  @product_quotation = Sale::ProductQuotation.last
  @titulobanner= "Nuestros Servicios"
  respond_to do |format|
    if params[:param_id_speciality]=='0' 
      params[:param_id_speciality]=''
    end
    if params[:search] && params[:param_id_speciality]==""
      format.html { @products = Product::Product.no_cero.activo.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    elsif params[:search]=="" && params[:param_id_speciality]
      format.html { @products = Product::Product.no_cero.activo.search_product_by_speciality(params[:param_id_speciality]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    elsif  params[:search] && params[:param_id_speciality] && params[:param_id_speciality]!=0
      format.html { @products = Product::Product.no_cero.activo.search(params[:search]).search_product_by_speciality(params[:param_id_speciality]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    else
      format.html { @products = Product::Product.no_cero.activo.order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    end
  end
end

def plist
  @titulobanner= "Nuestros Productos"
  if params[:param_id_speciality]=='0' 
    params[:param_id_speciality]=''
  end
  respond_to do |format|
    if params[:search] && params[:param_id_speciality]==""
      format.html { @products = Product::Product.no_cero.activo.pymes.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo.pymes }
      add_breadcrumb "Servicios", "/list"
    elsif params[:search]=="" && params[:param_id_speciality]
      format.html { @products = Product::Product.no_cero.activo.pymes.search_product_by_speciality(params[:param_id_speciality]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo.pymes }
      add_breadcrumb "Servicios", "/list"
    elsif  params[:search] && params[:param_id_speciality] && params[:param_id_speciality]!=0
      format.html { @products = Product::Product.no_cero.activo.pymes.search(params[:search]).search_product_by_speciality(params[:param_id_speciality]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @products = Product::Product.no_cero.activo.pymes }
      add_breadcrumb "Servicios", "/list"
    else
     format.html { @products = Product::Product.no_cero.activo.pymes.order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
     format.json { @products = Product::Product.no_cero.activo.pymes }
     add_breadcrumb "Servicios", "/list"
   end
 end
end

def details
  @product_providers = Product::Product.where(id: params[:id])
  @sale_product_quotation = Sale::ProductQuotation.new
  add_breadcrumb "Servicios", "/list"
  add_breadcrumb "#{@product_providers[0].name}", "#{params[:id]}"
  if params[:search]
    $search = params[:search]
  end
  if params[:param_id_speciality]
    $param_id_speciality = params[:param_id_speciality]
  end
  respond_to do |format|
    if params[:search]
      format.html { redirect_to list_search_path, search: "#{params[:search]}", param_id_speciality: "#{params[:param_id_speciality]}" } 
      format.json { @products = Product::Product.no_cero.activo }
      add_breadcrumb "Servicios", "/list"
    else 
      format.html { @products = Product::Product.no_cero.individual.activo.last(4) and @products2 = Product::Product.no_cero.pymes.activo.last(4) }
      format.json { @products = Product::Product.no_cero.activo }
    end
  end
end

def promotion
  @package_products = Colection::PackageProduct.where(colection_package_id: params[:id])
  @package = Colection::Package.find(params[:id])
  @sale_package_quotation = Sale::PackageQuotation.new
  add_breadcrumb "Paquetes y Promociones", "/promotions"
  add_breadcrumb "#{@package.description}", "#{params[:id]}"
  search(params[:search], params[:param_id_speciality])
end

def promotions
  @package_quotation = Sale::PackageQuotation.last
  @titulobanner= "Nuestras Promociones"
  respond_to do |format|
    if params[:search]
      format.html { @packages = Colection::Package.no_cero.activo.individual.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @packages = Colection::Package.no_cero.activo.individual.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      add_breadcrumb "Paquetes y Promociones", "/promotions"
    else
      format.html { @packages = Colection::Package.no_cero.activo.individual.order('created_at DESC').paginate(:page => params[:page], :per_page => 12) }
      format.json { @packages = Colection::Package.no_cero.activo.individual.order('created_at DESC').paginate(:page => params[:page], :per_page => 12) }
      add_breadcrumb "Paquetes y Promociones", "/promotions"
    end
  end
end

def pymes_promotions
  @package_quotation = Sale::PackageQuotation.last
  @titulobanner= "Nuestras Promociones"
  respond_to do |format|
    if params[:search]
      format.html { @packages = Colection::Package.no_cero.activo.pymes.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      format.json { @packages = Colection::Package.no_cero.activo.pymes.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 12) }
      add_breadcrumb "Paquetes y Promociones", "/pymes_promotions"
    else
      format.html { @packages = Colection::Package.no_cero.activo.pymes.order('created_at DESC').paginate(:page => params[:page], :per_page => 12) }

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/clinics.html.erb
 <div class="row">
   <% if !@provider_providers.present? %>
   <div class="alert alert-danger notice">
    <button type="button" class="close" data-dismiss="alert">&times;</button>   
    <p id="notice margin_left_none">No se han encontrado resultados.</p>
  </div>
  <% end %>
</div>

<% unless notice.nil? %>
<div class="row">
  <div class="alert alert-danger notice">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p id="notice margin_left_none"><%= notice %></p>
  </div>
</div>
<% end -%>
<div class="row">
  <div class="col-lg-12"> 
    <div class="breadcrumbs">
      <%= render_breadcrumbs :separator => ' / '%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12"> 
      <h2>Centros Médicos</h2>
  </div>
</div>
<div class="row">
  <% @provider_providers.each do |provider_provider| %>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail clinic-list">
      <%= link_to controller: "home" , action: "clinics_details", id: provider_provider do %>
      <div class="cont-img">
        <% if provider_provider.image_file_name.nil? %>
        <i class="fa fa-cube"></i>
        <%else%>
        <%= image_tag provider_provider.image.url(:large) %>
        <%end%>
      </div>

      <div class="mid-1">
        <div class="special_produc">
        </div>
        <p><i class="fa fa-map-marker" aria-hidden="true"></i><%= "#{provider_provider.address}" %></p>
        <p><i class="fa fa-phone" aria-hidden="true"></i><%= "#{provider_provider.phone.at(0..15)}" %>
          <% unless !(provider_provider.phone2.present? || provider_provider.phone3.present?) %>
          ...
          <%end%>
        </p>
        <p> <i class="fa fa-envelope" aria-hidden="true"></i><%= "#{provider_provider.email}" %></p>
      </div>
      <%end%>
    </div>
  </div>
  <%end%>
  <div class="col-lg-12">
    <div class="col-md-4 item-grid1 simpleCart_shelfItem">
      <%= will_paginate @provider_providers %>
    </div>
  </div>
</div>
<div class="row">
  <% if !@provider_providers.present? %>
  <div class="alert alert-danger notice">
    <button type="button" class="close" data-dismiss="alert">&times;</button>   
    <p id="notice margin_left_none">No se han encontrado resultados.</p>
  </div>
  <% end %>
</div>

app/views/home/clinics_details.html.erb
<div class="container">
  <div class="col-lg-12">
    <div class="breadcrumbs">
      <%= render_breadcrumbs :separator => ' / '%>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
      <div class="details-title"><%= @provider_providers.name %></div>
      <div class="flex-viewport" style="overflow: hidden; position: relative;">
        <% if @provider_providers.image_file_name.nil? %>
        <i class="fa fa-stethoscope"></i>
        <%else%>
        <%= image_tag @provider_providers.image.url(:medium) %>
        <%end%>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
      <nav class="nav-sidebar">
        <ul class="nav tabs">
          <li class="active"><a href="#tab1" data-toggle="tab">Información</a>
          </li>
          <li class=""><a href="#tab2" data-toggle="tab">Equipo Médico</a>
          </li>        </ul>
        </nav>
        <div class="tab-content one tab-clinic">
          <div class="tab-pane active text-style" id="tab1">
            <p class="ml-0"><img src="<%= asset_path 'pin_map.png' %>" alt="Novosalud"/> </i><%= @provider_providers.address %></p>
            <p class="ml-0"><img src="<%= asset_path 'phone_icon.png' %>" alt="Novosalud"/> <%= "#{@provider_providers.phone}"%> </p>
            <% unless !@provider_providers.phone2.present? %>
            <p class="ml-0"><img src="<%= asset_path 'phone_icon.png' %>" alt="Novosalud"/> 
              <%= "#{@provider_providers.phone2}" %>
            </p>
            <%end%>
            <% unless !@provider_providers.phone3.present?%>
            <p class="ml-0"><img src="<%= asset_path 'phone_icon.png' %>" alt="Novosalud"/> 
             <%= " #{@provider_providers.phone3}" %>
           </p>
           <% end %>
           <p class="ml-0"> <i class="fa fa-envelope" aria-hidden="true"></i><%= @provider_providers.email %></p>
         </div>
         <div class="tab-pane text-style" id="tab2">
          <ul class="pl-0">
           <% @provider_providers.provider_medico_providers.each do |provider_provider| %>
           <% unless provider_provider.nil? %>
           <li class="list-unstyled pl-0"><img src="<%= asset_path 'avatar.png' %>"> Dr. <%= provider_provider.provider_medico.people.first_name %><%= provider_provider.provider_medico.people.surname %> - <%= provider_provider.provider_medico.speciality.name %></li>
           <% end %>
           <%end%>
         </ul>
       </div>
     </div>
   </div>
 </div>
</div>

app/views/home/decision.html.erb
<section class="col-lg-10 col-lg-offset-1">
  <h1 align="center">Elige el segmento al que perteneces para continuar con la operación.</h1>
  <br>
  <div class="col-lg-12 center">
    <%= link_to "#{I18n.t ('.activerecord.models.people.one')}", { controller: "home", :action => :redireccionamiento_verificar,cliente: "persona"}, class: "hvr-skew-backward" %>
 
    <%= link_to "#{I18n.t ('.activerecord.models.companies.one')}", { controller: "home", :action => :redireccionamiento_verificar,cliente: "empresa"}, class: "hvr-skew-backward" %>
  </div>  
</section>

app/views/home/index.html.erb
<div class="container">
  <div class="page-header">
    <h3 class="titles">Nuevos productos</h3>
  </div>
  <div>
    <h4 class="">Individuales</h4>
  </div>
  <div class="row display-flex">
    <% @products.each do |product| %>
    <div class="col-xs-6 col-sm-4 col-md-3 flexbox">
      <div class="thumbnail wow slideInLeft">
        <%= link_to controller: "home" , action: "details", id: product do %>
        <div class="cont-img img-responsive center">
          <% if product.image_file_name.nil? %>
          <div class="ribbon new img-responsive">                                     
            <div class="theribbon"><%= I18n.t('.general.attribute.new_label') %>
            </div>
            <div class="ribbon-background">        
            </div>
          </div>
          <i class="fa fa-cube"></i>
          <%else%>
          <div class="ribbon new img-responsive">                                     
            <div class="theribbon"><%= I18n.t('.general.attribute.new_label') %>
            </div>
            <div class="ribbon-background">        
            </div>
          </div>
          <%= image_tag product.image.url(:large) %>
          <%end%>
        </div>
        <div class="mid-1">
          <div class="special_produc">
            <span>Bs. <%= number_with_precision(product.price.to_f, precision: 2,delimiter:'.',separator: ',') %></span>
          </div>
          <div class="special_produc product_soberano">
            <span>Bs. S <%= number_with_precision(product.price.to_f/100000, precision: 2,delimiter:'.',separator: ',') %></span>
          </div>
          <div class="name_product">
            <h6 class="p-0 m-0"><%= "#{product.name}"%></h6>
            <h6 class="p-0 m-0"><%= "#{product.provider_provider.name}" %></h6>
          </div>
        </div>
        <%end%>
      </div>
    </div>
    <%end%>

  </div>
  <div class="col-lg-12 col-md-12">
    <%= link_to I18n.t('.general.attribute.see_more') ,list_path, class: "float_right" %>
  </div>
  <div class="page-header">
    <h4>Empresas<!-- <small>Click add to cart</small> --></h4>
  </div>
  <div class="row display-flex" >
    <% @products2.each do |product| %>
    <div class="col-xs-6 col-sm-4 col-md-3 flexbox">
      <div class="thumbnail">
        <%= link_to controller: "home" , action: "details", id: product do %>
        <div class="cont-img img-responsive center">
          <% if product.image_file_name.nil? %>
          <div class="ribbon new img-responsive">                                     
            <div class="theribbon"><%= I18n.t('.general.attribute.new_label') %>
            </div>
            <div class="ribbon-background">        
            </div>
          </div>
          <i class="fa fa-cube"></i>
          <%else%>
          <div class="ribbon new img-responsive">                                     
            <div class="theribbon"><%= I18n.t('.general.attribute.new_label') %>
            </div>
            <div class="ribbon-background">        
            </div>
          </div>
          <%= image_tag product.image.url(:large) %>
          <%end%>
        </div>
        <div class="mid-1">
          <div class="special_produc">
            <span>Bs. <%= number_with_precision(product.price.to_f, precision: 2,delimiter:'.',separator: ',') %></span>
          </div>
          <div class="special_produc product_soberano">
            <span>Bs. S <%= number_with_precision(product.price.to_f/100000, precision: 2,delimiter:'.',separator: ',') %></span>
          </div>

          <div class="name_product">
            <h6 class="p-0 m-0"><%= "#{product.name}"%></h6>
            <h6 class="p-0 m-0"><%= "#{product.provider_provider.name}" %></h6>
          </div>
        </div>
        <%end%>
      </div>
    </div>
    <%end%>

  </div>
  <div class="col-lg-12 col-md-12">
    <%= link_to I18n.t('.general.attribute.see_more') ,plist_path, class: "float_right" %>
  </div>

</div>

<div style="text-align: center; margin-bottom: 30px; margin-top: 60px;">
          <video controls=""  controlslist="nodownload" autoplay="" width="50%" height="50%"><source src="http://novosalud.com.ve/wp-content/uploads/2015/12/Novo-en-línea.mp4" type="video/mp4"></video>
</div>