config/routes.rb
Rails.application.routes.draw do
  namespace :product do
    resources :products
  end
  root     "home#index"

  devise_for :users, controllers: {sessions: "users/sessions", passwords: 'users/passwords',  registrations: 'users/registrations', :confirmations => "users/confirmations" , :unlocks => 'users/unlocks'}
  #configuración para la gema auto-session-timeout
  devise_scope :user do
    match 'active'            => 'users/sessions#active',               via: :get  
    match 'timeout'           => 'users/sessions#timeout',              via: :get   
  end 
  
  get 'list', to: 'home#list'
  get 'list_search', to: 'home#list_search'
  get 'redireccionamiento_verificar', to: 'home#redireccionamiento_verificar'
  get 'plist', to: 'home#plist'
  get 'details/:id', to: 'home#details'
  get 'promotion/:id', to: 'home#promotion'
  get 'promotions', to: 'home#promotions'
  get 'pymes_promotions', to: 'home#pymes_promotions'
  get 'cart', to: 'home#cart'
  get 'quotation_history', to: 'home#quotation_history'
  get 'plan_history', to: 'home#plan_history'
  get 'expired_quotation', to: 'home#expired_quotation'
  get 'clinics', to: 'home#clinics'
  get 'clinics/:id', to: 'home#clinics_details'
  get 'admin', to: 'admin#index'
  get 'decision', to: 'home#decision'
  get 'message', to: 'home#message'
  get "blocked_user", to: "employees#blocked_user"
  get "forget_username", to: "employees#forget_username"
  get "forget_username_list", to: "employees#forget_username_list"
  get "forget_password", to: "employees#forget_password"
  post "check_send_username", to: "employees#check_send_username"
  get ':id/transference' , to: 'home#transference'
  get 'decision_transference', to: 'home#decision_transference'
  get 'profile', to: 'employees#profile'

  resources :people
  resources :organizations
  resources :initial_values
  resources :contacts

  resources :positions
    put "/positions/:id/inhabilitar", to:"positions#inhabilitar"
    put "/positions/:id/habilitar", to:"positions#habilitar"

  resources :specialities
    put "/specialities/:id/inhabilitar", to:"specialities#inhabilitar"
    put "/specialities/:id/habilitar", to:"specialities#habilitar"

  resources :banks
    put "/banks/:id/habilitar", to: "banks#habilitar"
    put "/banks/:id/inhabilitar", to: "banks#inhabilitar"

  resources :motives
    put "/motives/:id/inhabilitar", to:"motives#inhabilitar"
    put "/motives/:id/habilitar", to:"motives#habilitar"

  resources :method_payments
    put "/method_payments/:id/inhabilitar", to:"method_payments#inhabilitar"
    put "/method_payments/:id/habilitar", to:"method_payments#habilitar"

  resources :beneficiaries
    put "/beneficiaries/:id/inhabilitar", to: "beneficiaries#inhabilitar"
    put "/beneficiaries/:id/habilitar", to: "beneficiaries#habilitar"

  resources :customers
    put "/customers/:id/habilitar", to: "customers#habilitar"
    put "/customers/:id/inhabilitar", to: "customers#inhabilitar"

  resources :employees
    post "/employees/:id/habilitar", to: "employees#habilitar"
    post '/employees/:id/inhabilitar', to: "employees#inhabilitar"
    get '/employees/:id/motive', to: 'employees#motive'
    post "/employees/:id/eliminar_logico", to: "employees#eliminar_logico"
    put "/employees/:id/unblocked", to: "employees#unblocked"
    put "/employees/:id/resend_username", to: "employees#resend_username"
    put "/employees/:id/resend_password", to: "employees#resend_password"
    post '/employees/:id/update_user',to: 'employees#update_user'
    get "/employees/:id/redireccionamiento_eliminar", to: "employees#redireccionamiento_eliminar"
    get "/employees/:id/show_list", to: "employees#show_list"

  resources :accounts
    put "/accounts/:id/habilitar", to: "accounts#habilitar"
    put "/accounts/:id/inhabilitar", to: "accounts#inhabilitar"


  namespace :colection do
    resources :packages
      put "/packages/:id/habilitar", to: "packages#habilitar"
      put "/packages/:id/inhabilitar", to: "packages#inhabilitar"
      get "/packages/:id/destroy_package_product", to: "packages#destroy_package_product"
      get "/packages/:id/verificar_productos", to: "packages#verificar_productos"

    resources :package_products
  end

  namespace :product do
    resources :product_types
      put "/product_types/:id/inhabilitar", to:"product_types#inhabilitar"
      put "/product_types/:id/habilitar", to:"product_types#habilitar"

    resources :products
      put "/products/:id/inhabilitar", to:"products#inhabilitar"
      put "/products/:id/habilitar", to:"products#habilitar"

    resources :product_providers
  end

  namespace :business do
    resources :companies
      put "/company_types/:id/inhabilitar", to:"company_types#inhabilitar"
      put "/company_types/:id/habilitar", to:"company_types#habilitar"

    resources :company_types
      put "/companies/:id/inhabilitar", to:"companies#inhabilitar"
      put "/companies/:id/habilitar", to:"companies#habilitar"
  end

  namespace :security do
    resources :profiles
      post "/profiles/:id/inhabilitar", to:"profiles#inhabilitar"
      put "/profiles/:id/habilitar", to:"profiles#habilitar"
      get '/profiles/:id/motive', to: 'profiles#motive'

    resources :roles
      put "/roles/:id/inhabilitar", to:"roles#inhabilitar"
      put "/roles/:id/habilitar", to:"roles#habilitar"
      get 'redir', to: 'roles#redir'

    resources :role_types
      put "/role_types/:id/inhabilitar", to:"role_types#inhabilitar"
      put "/role_types/:id/habilitar", to:"role_types#habilitar"
    resources :role_type_menus
    resources :role_profiles
    resources :role_menus
  end

  namespace :provider do
    resources :provider_types
      put "/provider_types/:id/inhabilitar", to:"provider_types#inhabilitar"
      put "/provider_types/:id/habilitar", to:"provider_types#habilitar"

    resources :providers
      put "/providers/:id/inhabilitar", to:"providers#inhabilitar"
      put "/providers/:id/habilitar", to:"providers#habilitar"

    resources :medicos
      put "/medicos/:id/inhabilitar", to:"medicos#inhabilitar"
      put "/medicos/:id/habilitar", to:"medicos#habilitar"

    resources :medico_providers
  end

      get 'sale/quotations/reporte', to: "sale/quotations#reporte"
  namespace :sale do
    get 'actualizar_cantidad', to: 'package_quotations#actualizar_cantidad'
    get 'actualizar_cantidad_producto', to: 'product_quotations#actualizar_cantidad_producto'
    resources :quotations
      put "/quotations/:id/pagar", to:"quotations#pagar"
      put "/quotations/:id/cotizar", to:"quotations#cotizar"
      put "/quotations/:id/comprobante", to:"quotations#comprobante"
      put "/quotations/:id/reactivar", to:"quotations#reactivar"

      get 'quotations/:id/pay' , to: 'quotations#pay'
      get '/reactivar' , to: 'quotations#reactivate'
      get 'quotations/:id/view' , to: 'quotations#view'

    resources :package_quotations
    resources :product_quotations
  end

  namespace :payment do
    get 'contracted_products', to: "contracted_products#index"
    get 'contracted_products/:id', to: "contracted_products#show"
    resources :plans
    get 'plans_cierre' , to: 'plans#cierre'

    resources :transferences, only: [:new, :create]
  end

  namespace :service do
    resources :services
      put "/services/:id/reagendar", to: "services#reagendar"
      put "/services/:id/cancelar", to: "services#cancelar"
      put "/services/:id/anular", to: "services#anular"
    get 'reports' , to: 'services#report'

  end

  namespace :clinic do
    get 'clinic_service', to: "clinic_service#index"
    put "clinic_service/:id/atender", to: "clinic_service#atender"
    get 'reports', to: "clinic_service#report"
    get 'report_active', to: "clinic_service#report_active"
    get 'pending_date', to: "clinic_service#pending_date"
  end
  match '*path', to: redirect('/'), via: :all
end

app/models/security.rb
module Security
  def self.table_name_prefix
    'security_'
  end
end

app/models/security/menu.rb
class Security::Menu < ApplicationRecord
  belongs_to :parent, class_name: Security::Menu, foreign_key: "menu_id"
  has_many :children, class_name: Security::Menu, foreign_key: "menu_id"
  #Para la anexacion de nuevos opciones de menú para el canal administrativo se debe crear una nueva migración para tomar
  #como ejemplo revisar la migracion 20170427141057_add_menu_option.rb 
end

app/models/security/profile.rb
class Security::Profile < ApplicationRecord 
  belongs_to :security_role, class_name: Security::Role, foreign_key: :security_role_id
  has_many :employee, class_name: Employee, foreign_key: :security_profiles_id

 
	aasm column: "status"  do 
    state  :Activo, initial: true
    state  :Inactivo

    event :habilitar do
      transitions from: :Inactivo, to: :Activo
    end

    event :inhabilitar do
      transitions from: :Activo, to: :Inactivo,
                  after: [
                  :registrar_motivo
                  ]
    end
  end

  attr_accessor :motive, :user

  def registrar_motivo
    registrar_motivo = MotiveProfile.new
    registrar_motivo.user_created_id = self.user
    registrar_motivo.motive = self.motive
    registrar_motivo.profile_id = self.id
    registrar_motivo.status = "Inactivo"
    registrar_motivo.save
  end

  validates :name ,presence: true, uniqueness:{message:"Existe un registro con este nombre."}
  validates :security_role_id ,presence: true
  
  def self.search(search)
    where("name ILIKE ? OR cast(created_at as text) ILIKE ?" , "%#{search}%" , "%#{search}%")
  end
end

app/controllers/security/profiles_controller.rb
class Security::ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :verificar_permiso
  before_action :crear
  before_action :modificar
  before_action :eliminar
  before_action :consultar
  before_action :activar
  before_action :set_security_profile, only: [:show, :edit, :update, :destroy, :habilitar, :inhabilitar, :motive]
  before_action :title
  before_action :eliminarVariableGlobales, only: [:new]
  # GET /security/profiles
  # GET /security/profiles.json

  def index
    respond_to do |format|
      if params[:search]
        format.html { @security_profiles = Security::Profile.search(params[:search]).order("created_at DESC")}
        format.json { @security_profiles = Security::Profile.search(params[:search]).order("created_at DESC")}
      else
        format.html { @security_profiles = Security::Profile.all.order('created_at DESC')}
        format.json { @security_profiles = Security::Profile.all.order('created_at DESC')}
      end
    end
  end

  def motive
    
  end

  # GET /security/profiles/1
  # GET /security/profiles/1.json
  def show
   @motives_profile = MotiveProfile.where(profile_id: params[:id]).order("created_at DESC")  
   @role_profiles = Security::RoleProfile.where(security_profile_id: params[:id])
  end

  # GET /security/profiles/new
  def new
    @security_profile = Security::Profile.new
    @security_roles = Security::Role.all
    @security_role_types = Security::RoleType.all
    @security_role_profile = Security::RoleProfile.new
  end

  # GET /security/profiles/1/edit
  def edit
    @security_role_profile = Security::RoleProfile.new
    @role_profiles = Security::RoleProfile.where(security_profile_id: params[:id])
    @security_roles= Security::Role.all
    @security_role_types= Security::RoleType.all
    $profile =Security::Profile.find(params[:id])
  end

  # POST /security/profiles
  # POST /security/profiles.json
  def create
    @security_profile = Security::Profile.new(security_profile_params)
    @security_profile.user_created_id = current_user.id
    respond_to do |format|
      if @security_profile.save
        format.html { redirect_to security_profiles_path, notice: I18n.t('profiles.controller.create')}
        format.json { render :show, status: :created, location: @security_profile }
      else
        format.html { render :new }
        format.json { render json: @security_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /security/profiles/1
  # PATCH/PUT /security/profiles/1.json
  def update
    @security_profile.user_updated_id = current_user.id
    respond_to do |format|
      if @security_profile.update(security_profile_params)
        format.html { redirect_to security_profiles_path, notice: I18n.t('profiles.controller.update') }
        format.json { render :show, status: :ok, location: @security_profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

   def habilitar
    if @security_profile.habilitar!
      @security_profile.update(:user_updated_id => current_user.id)
      respond_to do |format|
        format.html { redirect_to security_profiles_path, notice: I18n.t('profiles.controller.enable')}
        format.json { head :no_content }
      end
    end
  end

  #Eliminar Logico
  def inhabilitar
    @security_profile.motive = params[:motive]
    @employees = Employee.find_by(security_profiles_id: @security_profile.id)
    unless params[:motive].empty?
      if @employees.nil?
        @security_profile.user = current_user.id
        if @security_profile.inhabilitar!
          @security_profile.update(:user_updated_id => current_user.id)
          redirect_to security_profiles_path, notice: I18n.t('profiles.controller.disable')
        end
      else
        flash[:errors] = I18n.t('general.action.response.profile.asigned_employee')
        redirect_to "/security/profiles/#{@security_profile.id}/motive"
      end
    else
      flash[:errors] = I18n.t('general.action.response.profile.disable_profile')
      redirect_to "/security/profiles/#{@security_profile.id}/motive"    
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_security_profile
      @security_profile = Security::Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def security_profile_params
      params.require(:security_profile).permit(
        :name,
        :user_created_id,
        :user_updated_id,
        :security_role_id
      )
    end

    def title
      @titulobanner =  I18n.t ('.general.models.profiles')
    end

    def eliminarVariableGlobales
      $profile =nil
    end

end

app/controllers/security/role_menus_controller.rb
class Security::RoleMenusController < ApplicationController
  before_action :authenticate_user!
  before_action :set_security_role_menu, only: [:show, :edit, :update, :destroy]
  before_action :verificar_permiso
  before_action :crear
  before_action :modificar
  before_action :eliminar
  before_action :activar
  # GET /security/role_menus
  # GET /security/role_menus.json
  def index
    @security_role_menus = Security::RoleMenu.all
  end

  # GET /security/role_menus/1
  # GET /security/role_menus/1.json
  def show
    @security_role_type_menu = Security::RoleTypeMenu.new
  end

  # GET /security/role_menus/new
  def new
    @security_role_menu = Security::RoleMenu.new
  end

  # GET /security/role_menus/1/edit
  def edit
    @security_role_type_menu = Security::RoleTypeMenu.where('security_role_menu_id = ?', params[:id])
  end

  # POST /security/role_menus
  # POST /security/role_menus.json
  def create
    @role_menu = Security::RoleMenu.new
    @role_menu.security_role_id = params[:id_role]
    @role_menu.security_menu_id = params[:id_menu]
     respond_to do |format|
      if @role_menu.save
        format.html { redirect_to @role_menu, notice: 'Menú creado exitosamente para este rol.' }
        format.json { render :show, status: :created, location: @role_menu }
        format.js   {} 
      else
        format.html { render :new }
        format.json { render json: @role_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /security/role_menus/1
  # PATCH/PUT /security/role_menus/1.json
  def update
    respond_to do |format|
      if @security_role_menu.update(security_role_menu_params)
        format.html { redirect_to @security_role_menu, notice: 'Menú actualizado exitosamente para este rol.' }
        format.json { render :show, status: :ok, location: @security_role_menu }
      else
        format.html { render :edit }
        format.json { render json: @security_role_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /security/role_menus/1
  # DELETE /security/role_menus/1.json
  def destroy
    @security_role = Security::Role.find_by(id: @security_role_menu.security_role.id)
    @security_role.update(:user_updated_id => current_user.id)
    @security_role_menu.destroy
    respond_to do |format|
      format.html { redirect_to security_role_menus_url, notice: 'Menú eliminado exitosamente para este rol.' }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_security_role_menu
      @security_role_menu = Security::RoleMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def security_role_menu_params
      params.require(:security_role_menu).permit(:security_role_id, :security_menu_id)
    end
end

app/helpers/security/profiles_helper.rb
module Security::ProfilesHelper
end

app/helpers/security/role_menus_helper.rb
module Security::RoleMenusHelper
end

app/helpers/security/role_profiles_helper.rb
module Security::RoleProfilesHelper
end

app/helpers/security/role_type_menus_helper.rb
module Security::RoleTypeMenusHelper
end

app/helpers/security/role_types_helper.rb
module Security::RoleTypesHelper
end

app/helpers/security/roles_helper.rb
module Security::RolesHelper
end

app/views/security/roles/_form.html.erb
<%= form_for(security_role) do |f| %>
<% if security_role.errors.any? %>
<% end %>
<div class="form-group col-lg-12">
  <div class=" <%= @security_role.errors[:name].any? ? "has-error has-feedback" : "" %> ">
    <%= f.label I18n.t('roles.attributes.name'), class:"label-form col-lg-12"%>
    <div class="controls col-lg-12 input_100">
      <%= f.text_field :name , minlength: '3', maxlength: '50'%>
      <span   class="help-inline">
        <%= @security_role.errors[:name].any? ? @security_role.errors[:name].to_s[/\w([^"]*)/] : "" %></span>
      </div>
    </div>
  </div>
  <div id="divAceptarProduct" class="form-group col-lg-12">
    <div class="col-lg-2 col-lg-offset-7 col-sm-2 col-sm-offset-7 col-md-2 col-md-offset-7">
      <%= link_to I18n.t('.general.action.cancel'), security_roles_path,class: "hvr-skew-backward" %>
    </div>
    <div   class="col-lg-3 pull-right">
    <% if @permiso_modificar == true || @permiso_crear == true%> 
      <%= f.submit I18n.t('roles.actions.accept'),class: "hvr-skew-backward",data: {disable_with: "Guardando ..."} %>
    <% end -%>
    </div>
  </div>
  <% end %>

app/views/security/roles/create.js.erb
$('#formRole').success();
$('#divAceptarRole').toggle();
$('#security_role_name').prop('disabled', true);
$('#securityRoleMenu').toggle();

app/views/security/roles/edit.html.erb
<section class="col-lg-8 col-lg-offset-2">
	<div class="col-lg-12">
		<h1 class="space-title">Editar Rol</h1>
	</div>
<%= render 'form', security_role: @security_role %>
</section>

app/views/security/roles/index.html.erb
<% unless notice.nil? %>
<div class="alert alert-success notice">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p id="notice"><%= notice %></p>
</div>
<% end -%>
<% unless alert.nil? %>
<div class="alert alert-danger notice">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p id="alert"><%= alert %></p>
</div>
<% end -%>
<section class="container table_flex_five">
  <h1 class="space-title"><%=raw I18n.t ('.general.titles.role_menus') %></h1>
  <table id="datatable" class="table table-hover roles">
    <thead>
    <% @security_roles.each do |security_role| %>
      <tr>
        <th><%= raw I18n.t('.general.attribute.name') %></th>
        <th><%= raw I18n.t('.general.attribute.created_by') %></th>
        <th><%= raw I18n.t('.general.attribute.created_at') %></th>
        <th><%= raw I18n.t('.general.attribute.updated_by') %></th>
        <th><%= raw I18n.t('.general.attribute.updated_at') %></th>
        <th><%= raw I18n.t('.general.attributes.actions') %></th>
      </tr>
      <% end %>
    </thead>
    <tbody>
    <% @security_roles.each do |security_role| %>
      <tr>
        <td><%= security_role.name %></td>
        <td><%= security_role.usuario(security_role.user_created_id) %></td>
        <td><%= security_role.created_at.strftime("%d-%m-%Y")  %></td>
        <td><%= security_role.usuario(security_role.user_updated_id) %></td>
        <td><%= security_role.updated_at.strftime("%d-%m-%Y")  %></td>
        <td>
          <%= link_to security_role, class: "hvr-skew-backward", :data => {:toggle=>"tooltip"}, 'title' => "Ver" do %>
          <%= content_tag(:i, nil, class: ["glyphicon", "glyphicon-eye-open"] ) %>
          <%= content_tag(:span, "Configurar") %>
          <% end %>
          <% if @permiso_modificar == true %> 
            <%= link_to edit_security_role_path(security_role), class: "hvr-skew-backward", :data => {:toggle=>"tooltip"}, 'title' => "Modificar" do %>
              <%= content_tag(:i, nil, class: ["glyphicon", "glyphicon-pencil"] ) %>
              <%= content_tag(:span, I18n.t(".general.action.edit")) %>
            <% end %>
          <% end -%>
          <% if @permiso_activar == true %> 
            <% if security_role.may_inhabilitar? %>
              <%= link_to "/security/roles/#{security_role.id}/inhabilitar", method: :put, data: { confirm: I18n.t('.general.action.question.role.disable')}, class: "hvr-skew-backward", :data => {:toggle=>"tooltip"}, 'title' => "Desactivar" do %>
                <%= content_tag(:i, nil, class: ["glyphicon", "glyphicon-off"] ) %>
                <%= content_tag(:span, I18n.t(".general.action.disable")) %>
              <% end %>
            <%else%>
              <%= link_to "/security/roles/#{security_role.id}/habilitar", method: :put, data: { confirm: I18n.t('.general.action.question.role.enable')}, class: "hvr-skew-backward", :data => {:toggle=>"tooltip"}, 'title' => "Activar" do %>
                <%= content_tag(:i, nil, class: ["glyphicon", "glyphicon-off"] ) %>
                <%= content_tag(:span, I18n.t(".general.action.enable")) %>
              <% end %>
            <% end -%>
        <%end%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% if @permiso_crear == true%> 
    <%= link_to new_security_role_path,  class: "hvr-skew-backward"  do %>
    <%= content_tag(:span, I18n.t('.general.action.register') << " " << I18n.t('.general.model.role')) %>
    <% end %>
  <% end -%>
  <% if !@security_roles.present? %>
  <div class="alert alert-danger notice col-lg-12 ml-0">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <p><%= raw I18n.t('.general.attribute.list_empty') %></p>
  </div>
  <% end %>
</section>

app/views/security/roles/new.html.erb
<section class="col-lg-8 col-lg-offset-2">
	<div class="col-lg-12">
		<h1 class="space-title">Registrar Rol</h1>
	</div>
	<%= render 'form', security_role: @security_role %>
</section>

app/views/security/roles/show.html.erb
<% unless notice.nil? %>
<div class="alert alert-success notice">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <p id="notice"><%= notice %></p> 
</div>
<% end -%> 
<p>
  <strong> <%= raw I18n.t('.roles.attributes.name')%> </strong>
  <%= @security_role.name %>
</p>
<br>
<h1>Opciones para visibilidad</h1>
<br>
<section class="menu_content">
  <div class= "col-lg-12">
    <div class="panel-group col-lg-6" id="accordion">
      <h2>Opciones a elegir</h2>
      <% @opciones.select{|padre| padre.menu_id == nil }.each do |menus| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= menus.id%>"><%= raw menus.description %></a>
          </h2>
        </div>
        <% unless menus.is_father? %>
        <% if @permiso_modificar == true || @permiso_crear == true%> 
          <%= link_to "", { controller: "security/role_type_menus", :action => :new, id_menu: menus.id, id_role: params[:id]}, remote: true, class: "btn btn-primary pull-right fa fa-key" %>
        <% end -%>
        <%end%>
        <div id="collapse<%= menus.id%>" class="panel-collapse collapse">
          <div class="panel-body">
            <% @opciones.select{|hijo| hijo.menu_id == menus.id }.each do |menuhijo| %>
            <div class="col-lg-12">
              <div class="col-lg-12 form-group">
                <% unless menuhijo.is_father? %>
                <div class="col-lg-8">
                  <%= render inline: menuhijo.codemenu %>
                </div>
                <div class="col-lg-4">
                <% if @permiso_modificar == true || @permiso_crear == true%> 
                  <%= link_to "", { controller: "security/role_type_menus", :action => :new, id_menu: menuhijo.id, id_role: params[:id]}, remote: true, class: "btn btn-primary pull-right fa fa-key" %>
                <% end -%>
                </div>
                <%else%>
                <div class="col-lg-12">
                  <h2><%= render inline: menuhijo.codemenu %></h2>
                </div>
                <%end%>
                <br>
              </div>
            </div>
            <% @opciones.select{|hijo2| hijo2.menu_id == menuhijo.id }.each do |menuhijo2| %>
            <div class="col-lg-12">
              <div class="col-lg-12 form-group">
                <div class="col-lg-8">
                  <%= render inline: menuhijo2.codemenu %>
                </div>

                <% unless menuhijo2.is_father? %>
                <div class="col-lg-4">
                  <% if @permiso_modificar == true || @permiso_crear == true%> 
                    <%= link_to "", { controller: "security/role_type_menus", :action => :new, id_menu: menuhijo2.id, id_role: params[:id]}, remote: true, class: "btn btn-primary pull-right fa fa-key" %>
                  <% end -%>
                </div>
                <%end%>
              </div>
            </div>
            <% end -%>
            <% end -%>
          </div>
        </div>
      </div> 
      <% end -%>
    </div> 
    <div id="securityRoleMenu" class="col-lg-6" >
      <h2>Opciones de menú actuales</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Menú</th>
            <th colspan="3">Acciones</th>
          </tr>
        </thead>
        <tbody id="roles_menu">
          <%= render @role_menu %>
        </tbody>
      </table>
    </div>
  </div>
</section>
    <div class="col-lg-2 col-lg-offset-7">
          <%= link_to security_redir_path,method: :get, data: { confirm: I18n.t('.general.action.question.role.finaled')}, class: "hvr-skew-backward" do %>
          <%= content_tag(:span, I18n.t('.general.action.finaled')) %>
          <% end %>
    </div>